version: '3.8'

services:
  searchbox-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      # Mount source code for hot reloading
      - .:/app
      - /app/node_modules
      - /app/.next
      # Persist FAISS indexes
      - faiss-indexes:/app/faiss-indexes
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  faiss-indexes:
