name: SearchBox App CI/CD
on: [push, pull_request]
jobs:
  e2e:
    name: 'Build + E2E tests'
    env:
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.5.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium

      - name: Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Type check
        run: pnpm run typecheck

      - name: Build application
        run: pnpm run build

      - name: Run E2E tests
        run: pnpm run test-e2e

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            playwright/test-results
          retention-days: 7

  unit:
    name: 'Unit tests + Linting'
    env:
      NODE_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 8.5.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Type check
        run: pnpm run typecheck

      - name: Lint code
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test-unit

      - name: Upload coverage reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage
          retention-days: 7
